blank_issues_enabled: false
contact_links:
  - name: BidMachine Unity Plugin Documentation
    url: https://developers.bidmachine.io/sdk/general/unity/overview
    about: The place to get started with BidMachine Unity Plugin.
